name: ordem_servico
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # --- Gerenciamento de Estado ---
  flutter_bloc:
  bloc: 9.1.0

  # --- Injeção de Dependência ---
  get_it: ^7.7.0
  injectable: ^2.4.2

  # --- Armazenamento Local ---
  sqflite: ^2.4.2

  # --- Utilitários (Hardware/Plugins) ---
  image_picker:

  # --- Icons ---
  cupertino_icons: ^1.0.8
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # --- Geração de Código (Code-gen) ---
  build_runner:
  injectable_generator:

  # --- Linting ---
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic